<?php
/**
 * Created by PhpStorm.
 * User: qiwenzhi
 * Date: 2018/8/3
 * Time: 下午3:55
 */

namespace api\controllers;

use Yii;
use yii\rest\ActiveController;
use api\models\LoginForm;

class UserController extends ActiveController
{
    public $modelClass = 'common\models\User';

    public function actions()
    {
        $action= parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
    }

    public function actionIndex()
    {
        //你的代码
    }

    public function actionSendEmail()  //假如是get请求
    {
        //业务逻辑
    }

    public function actionLogin()
    {
        $model = new LoginForm();
        if ($model->load(Yii::$app->getRequest()->getBodyParams(), '') && $model->login()) {
            return [
                'access_token' => $model->login(),
            ];
        } else {
            return $model->getFirstErrors();
        }
    }
}